language: cpp

os: linux
dist: bionic
sudo: false

addons:
  apt:
    packages:
      - parallel

compiler:
  - gcc
  - clang

script:
  - ./ci/build.sh
  - ./check_includes.sh

notifications:
  email: false
  irc:
    channels:
      - "ircs://chat.freenode.net:6697/#mcfproj"
    template:
      - "[ lh_mouse %{repository_slug}#%{commit}] %{result} on %{branch} by %{author} (%{build_url})"
